
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class ListMovementWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvMovements;

		private global::Gtk.Button btBack;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.ListMovementWindow
			this.Name = "CutreGest.view.windows.ListMovementWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ListMovementWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CutreGest.view.windows.ListMovementWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvMovements = new global::Gtk.TreeView();
			this.tvMovements.CanFocus = true;
			this.tvMovements.Name = "tvMovements";
			this.GtkScrolledWindow.Add(this.tvMovements);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btBack = new global::Gtk.Button();
			this.btBack.CanFocus = true;
			this.btBack.Name = "btBack";
			this.btBack.UseUnderline = true;
			this.btBack.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.vbox2.Add(this.btBack);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.btBack]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
