
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class ListArticleWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action usersAction;

		private global::Gtk.Action categoriesAction;

		private global::Gtk.Action AlmacnAction;

		private global::Gtk.Action articleAddAction;

		private global::Gtk.Action articleEditAction;

		private global::Gtk.Action articleRemoveAction;

		private global::Gtk.Action articleRefreshAction;

		private global::Gtk.Action exitAction;

		private global::Gtk.Action MostrarStocksAction;

		private global::Gtk.Action MostrarMovimientosAction;

		private global::Gtk.Action MostrarCategorasAction;

		private global::Gtk.Action aboutAction;

		private global::Gtk.Action movementAddAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar mBar;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvArticles;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.ListArticleWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.usersAction = new global::Gtk.Action("usersAction", global::Mono.Unix.Catalog.GetString("Usuarios"), null, null);
			this.usersAction.HideIfEmpty = false;
			this.usersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Usuarios");
			w1.Add(this.usersAction, null);
			this.categoriesAction = new global::Gtk.Action("categoriesAction", global::Mono.Unix.Catalog.GetString("Categorías"), null, null);
			this.categoriesAction.HideIfEmpty = false;
			this.categoriesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Categorías");
			w1.Add(this.categoriesAction, null);
			this.AlmacnAction = new global::Gtk.Action("AlmacnAction", global::Mono.Unix.Catalog.GetString("Almacén"), null, null);
			this.AlmacnAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Movimientos");
			w1.Add(this.AlmacnAction, null);
			this.articleAddAction = new global::Gtk.Action("articleAddAction", null, null, "gtk-add");
			w1.Add(this.articleAddAction, null);
			this.articleEditAction = new global::Gtk.Action("articleEditAction", null, null, "gtk-edit");
			w1.Add(this.articleEditAction, null);
			this.articleRemoveAction = new global::Gtk.Action("articleRemoveAction", null, null, "gtk-remove");
			w1.Add(this.articleRemoveAction, null);
			this.articleRefreshAction = new global::Gtk.Action("articleRefreshAction", null, null, "gtk-refresh");
			w1.Add(this.articleRefreshAction, null);
			this.exitAction = new global::Gtk.Action("exitAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
			this.exitAction.HideIfEmpty = false;
			this.exitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir                               ");
			w1.Add(this.exitAction, null);
			this.MostrarStocksAction = new global::Gtk.Action("MostrarStocksAction", global::Mono.Unix.Catalog.GetString("Mostrar Stocks"), null, null);
			this.MostrarStocksAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Mostrar Stocks");
			w1.Add(this.MostrarStocksAction, null);
			this.MostrarMovimientosAction = new global::Gtk.Action("MostrarMovimientosAction", global::Mono.Unix.Catalog.GetString("Mostrar movimientos"), null, null);
			this.MostrarMovimientosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Mostrar movimientos");
			w1.Add(this.MostrarMovimientosAction, null);
			this.MostrarCategorasAction = new global::Gtk.Action("MostrarCategorasAction", global::Mono.Unix.Catalog.GetString("Mostrar categorías"), null, null);
			this.MostrarCategorasAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Mostrar categorías");
			w1.Add(this.MostrarCategorasAction, null);
			this.aboutAction = new global::Gtk.Action("aboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
			this.aboutAction.HideIfEmpty = false;
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
			w1.Add(this.aboutAction, null);
			this.movementAddAction = new global::Gtk.Action("movementAddAction", global::Mono.Unix.Catalog.GetString("Nuevo movimiento"), null, "gtk-add");
			this.movementAddAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Nuevo movimiento");
			w1.Add(this.movementAddAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "CutreGest.view.windows.ListArticleWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Artículos - Lista");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 350;
			this.DefaultHeight = 400;
			this.Decorated = false;
			// Container child CutreGest.view.windows.ListArticleWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='mBar'><menuitem name='usersAction' action='usersAction'/><menuitem name='categoriesAction' action='categoriesAction'/><menu name='AlmacnAction' action='AlmacnAction'><menuitem name='MostrarMovimientosAction' action='MostrarMovimientosAction'/><menuitem name='movementAddAction' action='movementAddAction'/></menu><menuitem name='aboutAction' action='aboutAction'/><menuitem name='exitAction' action='exitAction'/></menubar></ui>");
			this.mBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/mBar")));
			this.mBar.Name = "mBar";
			this.vbox1.Add(this.mBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.mBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar1'><toolitem name='articleAddAction' action='articleAddAction'/><toolitem name='articleEditAction' action='articleEditAction'/><toolitem name='articleRemoveAction' action='articleRemoveAction'/><toolitem name='articleRefreshAction' action='articleRefreshAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvArticles = new global::Gtk.TreeView();
			this.tvArticles.WidthRequest = 300;
			this.tvArticles.HeightRequest = 350;
			this.tvArticles.CanFocus = true;
			this.tvArticles.Name = "tvArticles";
			this.tvArticles.Reorderable = true;
			this.GtkScrolledWindow.Add(this.tvArticles);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w5.Position = 2;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
