
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class MovementWindow
	{
		private global::Gtk.Table table2;

		private global::Gtk.Button btBack;

		private global::Gtk.Button btSubmit;

		private global::Gtk.ComboBox comboArticles;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.RadioButton rbIn;

		private global::Gtk.RadioButton rbOut;

		private global::Gtk.SpinButton spinAmmount;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.MovementWindow
			this.Name = "CutreGest.view.windows.MovementWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Nuevo movimiento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(15));
			this.Resizable = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			// Container child CutreGest.view.windows.MovementWindow.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.btBack = new global::Gtk.Button();
			this.btBack.CanFocus = true;
			this.btBack.Name = "btBack";
			this.btBack.UseUnderline = true;
			this.btBack.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.table2.Add(this.btBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.btBack]));
			w1.TopAttach = ((uint)(3));
			w1.BottomAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btSubmit = new global::Gtk.Button();
			this.btSubmit.CanFocus = true;
			this.btSubmit.Name = "btSubmit";
			this.btSubmit.UseUnderline = true;
			this.btSubmit.Label = global::Mono.Unix.Catalog.GetString("Efectuar movimiento");
			this.table2.Add(this.btSubmit);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.btSubmit]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.comboArticles = global::Gtk.ComboBox.NewText();
			this.comboArticles.Name = "comboArticles";
			this.table2.Add(this.comboArticles);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.comboArticles]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Artículo");
			this.table2.Add(this.label6);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.label6]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad");
			this.table2.Add(this.label7);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.label7]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.rbIn = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Entrada"));
			this.rbIn.CanFocus = true;
			this.rbIn.Name = "rbIn";
			this.rbIn.DrawIndicator = true;
			this.rbIn.UseUnderline = true;
			this.rbIn.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.table2.Add(this.rbIn);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.rbIn]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.rbOut = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Salida"));
			this.rbOut.CanFocus = true;
			this.rbOut.Name = "rbOut";
			this.rbOut.DrawIndicator = true;
			this.rbOut.UseUnderline = true;
			this.rbOut.Group = this.rbIn.Group;
			this.table2.Add(this.rbOut);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.rbOut]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinAmmount = new global::Gtk.SpinButton(0D, 1000D, 1D);
			this.spinAmmount.CanFocus = true;
			this.spinAmmount.Name = "spinAmmount";
			this.spinAmmount.Adjustment.PageIncrement = 10D;
			this.spinAmmount.ClimbRate = 1D;
			this.spinAmmount.Numeric = true;
			this.spinAmmount.Value = 1D;
			this.table2.Add(this.spinAmmount);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2[this.spinAmmount]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 323;
			this.DefaultHeight = 159;
			this.Show();
		}
	}
}
