
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class CategoryWindow
	{
		private global::Gtk.Table table1;

		private global::Gtk.Entry entryCategoryName;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btBack;

		private global::Gtk.Button btSubmit;

		private global::Gtk.Label label3;

		private global::Gtk.Label labelCategoryId;

		private global::Gtk.Label labelId;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.CategoryWindow
			this.Name = "CutreGest.view.windows.CategoryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Categorías - Detalle");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(20));
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child CutreGest.view.windows.CategoryWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.entryCategoryName = new global::Gtk.Entry();
			this.entryCategoryName.CanFocus = true;
			this.entryCategoryName.Name = "entryCategoryName";
			this.entryCategoryName.IsEditable = true;
			this.entryCategoryName.InvisibleChar = '•';
			this.table1.Add(this.entryCategoryName);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.entryCategoryName]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btBack = new global::Gtk.Button();
			this.btBack.CanFocus = true;
			this.btBack.Name = "btBack";
			this.btBack.UseUnderline = true;
			this.btBack.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.hbuttonbox1.Add(this.btBack);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btBack]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btSubmit = new global::Gtk.Button();
			this.btSubmit.CanDefault = true;
			this.btSubmit.CanFocus = true;
			this.btSubmit.Name = "btSubmit";
			this.btSubmit.UseUnderline = true;
			this.btSubmit.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbuttonbox1.Add(this.btSubmit);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btSubmit]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.table1.Add(this.hbuttonbox1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.hbuttonbox1]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Categoría");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelCategoryId = new global::Gtk.Label();
			this.labelCategoryId.Name = "labelCategoryId";
			this.labelCategoryId.LabelProp = global::Mono.Unix.Catalog.GetString("Category ID");
			this.table1.Add(this.labelCategoryId);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.labelCategoryId]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelId = new global::Gtk.Label();
			this.labelId.Name = "labelId";
			this.labelId.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.table1.Add(this.labelId);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.labelId]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 283;
			this.DefaultHeight = 125;
			this.btSubmit.HasDefault = true;
			this.Show();
		}
	}
}
