
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class ListUserWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action addAction;

		private global::Gtk.Action editAction;

		private global::Gtk.Action removeAction;

		private global::Gtk.Action refreshAction;

		private global::Gtk.Action closeAction;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Toolbar toolbar2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvUsers;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.ListUserWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.addAction = new global::Gtk.Action("addAction", null, null, "gtk-add");
			w1.Add(this.addAction, null);
			this.editAction = new global::Gtk.Action("editAction", null, null, "gtk-edit");
			w1.Add(this.editAction, null);
			this.removeAction = new global::Gtk.Action("removeAction", null, null, "gtk-remove");
			w1.Add(this.removeAction, null);
			this.refreshAction = new global::Gtk.Action("refreshAction", null, null, "gtk-refresh");
			w1.Add(this.refreshAction, null);
			this.closeAction = new global::Gtk.Action("closeAction", null, null, "gtk-close");
			w1.Add(this.closeAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "CutreGest.view.windows.ListUserWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Usuarios - Lista");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(15));
			this.Decorated = false;
			this.DestroyWithParent = true;
			// Container child CutreGest.view.windows.ListUserWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar2'><toolitem name='addAction' action='addAction'/><toolitem name='editAction' action='editAction'/><toolitem name='removeAction' action='removeAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='closeAction' action='closeAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.vbox3.Add(this.toolbar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.toolbar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvUsers = new global::Gtk.TreeView();
			this.tvUsers.CanFocus = true;
			this.tvUsers.Name = "tvUsers";
			this.GtkScrolledWindow.Add(this.tvUsers);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w4.Position = 1;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 300;
			this.DefaultHeight = 251;
			this.Show();
		}
	}
}
