
// This file has been generated by the GUI designer. Do not modify.
namespace CutreGest.view.windows
{
	public partial class ArticleWindow
	{
		private global::Gtk.Table table1;

		private global::Gtk.Button btBack;

		private global::Gtk.Button btSubmit;

		private global::Gtk.ComboBox cbProductCategory;

		private global::Gtk.Entry entryProductName;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelId;

		private global::Gtk.Label labelProductId;

		private global::Gtk.SpinButton spinCurrentStock;

		private global::Gtk.SpinButton spinMaxStock;

		private global::Gtk.SpinButton spinMinStock;

		private global::Gtk.SpinButton spinProductPrice;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CutreGest.view.windows.ArticleWindow
			this.Name = "CutreGest.view.windows.ArticleWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Artículos - Detalle");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			// Container child CutreGest.view.windows.ArticleWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(8)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(15));
			// Container child table1.Gtk.Table+TableChild
			this.btBack = new global::Gtk.Button();
			this.btBack.CanFocus = true;
			this.btBack.Name = "btBack";
			this.btBack.UseUnderline = true;
			this.btBack.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.table1.Add(this.btBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.btBack]));
			w1.TopAttach = ((uint)(7));
			w1.BottomAttach = ((uint)(8));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btSubmit = new global::Gtk.Button();
			this.btSubmit.CanDefault = true;
			this.btSubmit.CanFocus = true;
			this.btSubmit.Name = "btSubmit";
			this.btSubmit.UseUnderline = true;
			this.btSubmit.Label = global::Mono.Unix.Catalog.GetString("Aceptar");
			this.table1.Add(this.btSubmit);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.btSubmit]));
			w2.TopAttach = ((uint)(7));
			w2.BottomAttach = ((uint)(8));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbProductCategory = global::Gtk.ComboBox.NewText();
			this.cbProductCategory.Name = "cbProductCategory";
			this.table1.Add(this.cbProductCategory);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.cbProductCategory]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryProductName = new global::Gtk.Entry();
			this.entryProductName.CanFocus = true;
			this.entryProductName.Name = "entryProductName";
			this.entryProductName.IsEditable = true;
			this.entryProductName.InvisibleChar = '•';
			this.table1.Add(this.entryProductName);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.entryProductName]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Stock");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("MinStock");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w6.TopAttach = ((uint)(5));
			w6.BottomAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Producto");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Categoría");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Precio");
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("MaxStock");
			this.table1.Add(this.label6);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
			w10.TopAttach = ((uint)(6));
			w10.BottomAttach = ((uint)(7));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelId = new global::Gtk.Label();
			this.labelId.Name = "labelId";
			this.labelId.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.table1.Add(this.labelId);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.labelId]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelProductId = new global::Gtk.Label();
			this.labelProductId.Name = "labelProductId";
			this.labelProductId.LabelProp = global::Mono.Unix.Catalog.GetString("Product ID");
			this.table1.Add(this.labelProductId);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.labelProductId]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinCurrentStock = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinCurrentStock.CanFocus = true;
			this.spinCurrentStock.Name = "spinCurrentStock";
			this.spinCurrentStock.Adjustment.PageIncrement = 10D;
			this.spinCurrentStock.ClimbRate = 1D;
			this.spinCurrentStock.Numeric = true;
			this.table1.Add(this.spinCurrentStock);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.spinCurrentStock]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinMaxStock = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinMaxStock.CanFocus = true;
			this.spinMaxStock.Name = "spinMaxStock";
			this.spinMaxStock.Adjustment.PageIncrement = 10D;
			this.spinMaxStock.ClimbRate = 1D;
			this.spinMaxStock.Numeric = true;
			this.table1.Add(this.spinMaxStock);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.spinMaxStock]));
			w14.TopAttach = ((uint)(6));
			w14.BottomAttach = ((uint)(7));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinMinStock = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinMinStock.CanFocus = true;
			this.spinMinStock.Name = "spinMinStock";
			this.spinMinStock.Adjustment.PageIncrement = 10D;
			this.spinMinStock.ClimbRate = 1D;
			this.spinMinStock.Numeric = true;
			this.table1.Add(this.spinMinStock);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.spinMinStock]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinProductPrice = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinProductPrice.CanFocus = true;
			this.spinProductPrice.Name = "spinProductPrice";
			this.spinProductPrice.Adjustment.PageIncrement = 10D;
			this.spinProductPrice.ClimbRate = 1D;
			this.spinProductPrice.Digits = ((uint)(2));
			this.spinProductPrice.Numeric = true;
			this.table1.Add(this.spinProductPrice);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.spinProductPrice]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 353;
			this.DefaultHeight = 284;
			this.btSubmit.HasDefault = true;
			this.Show();
		}
	}
}
