
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.Button btExit;

	private global::Gtk.Button btLogin;

	private global::Gtk.Entry entryUserName;

	private global::Gtk.Entry entryUserPass;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(5));
		// Container child table1.Gtk.Table+TableChild
		this.btExit = new global::Gtk.Button();
		this.btExit.CanFocus = true;
		this.btExit.Name = "btExit";
		this.btExit.UseUnderline = true;
		this.btExit.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.table1.Add(this.btExit);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.btExit]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btLogin = new global::Gtk.Button();
		this.btLogin.CanDefault = true;
		this.btLogin.CanFocus = true;
		this.btLogin.Name = "btLogin";
		this.btLogin.UseUnderline = true;
		this.btLogin.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.table1.Add(this.btLogin);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.btLogin]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryUserName = new global::Gtk.Entry();
		this.entryUserName.CanFocus = true;
		this.entryUserName.Name = "entryUserName";
		this.entryUserName.IsEditable = true;
		this.entryUserName.MaxLength = 64;
		this.entryUserName.InvisibleChar = '•';
		this.table1.Add(this.entryUserName);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.entryUserName]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryUserPass = new global::Gtk.Entry();
		this.entryUserPass.CanFocus = true;
		this.entryUserPass.Name = "entryUserPass";
		this.entryUserPass.IsEditable = true;
		this.entryUserPass.Visibility = false;
		this.entryUserPass.InvisibleChar = '•';
		this.table1.Add(this.entryUserPass);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.entryUserPass]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 272;
		this.DefaultHeight = 105;
		this.btLogin.HasDefault = true;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
