
// This file has been generated by the GUI designer. Do not modify.
namespace CGtk.Articulo
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action addAction;

		private global::Gtk.Action editAction;

		private global::Gtk.Action removeAction;

		private global::Gtk.Action refreshAction;

		private global::Gtk.Action closeAction;

		private global::Gtk.Action CategoraAction;

		private global::Gtk.Action ArtculoAction;

		private global::Gtk.Action showCategories;

		private global::Gtk.Action createCategory;

		private global::Gtk.Action showArticles;

		private global::Gtk.Action createArticle;

		private global::Gtk.VBox vBox;

		private global::Gtk.MenuBar menubar4;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CGtk.Articulo.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.addAction = new global::Gtk.Action("addAction", null, null, "gtk-add");
			w1.Add(this.addAction, null);
			this.editAction = new global::Gtk.Action("editAction", null, null, "gtk-edit");
			w1.Add(this.editAction, null);
			this.removeAction = new global::Gtk.Action("removeAction", null, null, "gtk-remove");
			w1.Add(this.removeAction, null);
			this.refreshAction = new global::Gtk.Action("refreshAction", null, null, "gtk-refresh");
			w1.Add(this.refreshAction, null);
			this.closeAction = new global::Gtk.Action("closeAction", null, null, "gtk-close");
			w1.Add(this.closeAction, null);
			this.CategoraAction = new global::Gtk.Action("CategoraAction", global::Mono.Unix.Catalog.GetString("Categoría"), null, null);
			this.CategoraAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Categoría");
			w1.Add(this.CategoraAction, null);
			this.ArtculoAction = new global::Gtk.Action("ArtculoAction", global::Mono.Unix.Catalog.GetString("Artículo"), null, null);
			this.ArtculoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Artículo");
			w1.Add(this.ArtculoAction, null);
			this.showCategories = new global::Gtk.Action("showCategories", global::Mono.Unix.Catalog.GetString("Listar categorías"), null, null);
			this.showCategories.ShortLabel = global::Mono.Unix.Catalog.GetString("Listar");
			w1.Add(this.showCategories, null);
			this.createCategory = new global::Gtk.Action("createCategory", global::Mono.Unix.Catalog.GetString("Nueva categoría"), null, null);
			this.createCategory.ShortLabel = global::Mono.Unix.Catalog.GetString("Nueva");
			w1.Add(this.createCategory, null);
			this.showArticles = new global::Gtk.Action("showArticles", global::Mono.Unix.Catalog.GetString("Listar artículos"), null, null);
			this.showArticles.ShortLabel = global::Mono.Unix.Catalog.GetString("Listar artículos");
			w1.Add(this.showArticles, null);
			this.createArticle = new global::Gtk.Action("createArticle", global::Mono.Unix.Catalog.GetString("Nuevo artículo"), null, null);
			this.createArticle.ShortLabel = global::Mono.Unix.Catalog.GetString("Nuevo artículo");
			w1.Add(this.createArticle, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "CGtk.Articulo.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CGtk.Articulo.MainWindow.Gtk.Container+ContainerChild
			this.vBox = new global::Gtk.VBox();
			this.vBox.Name = "vBox";
			this.vBox.Spacing = 6;
			// Container child vBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar4\'><menu name=\'CategoraAction\' action=\'CategoraAction\'>" +
					"<menuitem name=\'showCategories\' action=\'showCategories\'/><menuitem name=\'createC" +
					"ategory\' action=\'createCategory\'/></menu></menubar></ui>");
			this.menubar4 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar4")));
			this.menubar4.Name = "menubar4";
			this.vBox.Add(this.menubar4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBox[this.menubar4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar1'><toolitem name='addAction' action='addAction'/><toolitem name='editAction' action='editAction'/><toolitem name='removeAction' action='removeAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='closeAction' action='closeAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vBox.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.GtkScrolledWindow.Add(this.treeView);
			this.vBox.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vBox[this.GtkScrolledWindow]));
			w5.Position = 2;
			this.Add(this.vBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 485;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
