
// This file has been generated by the GUI designer. Do not modify.
namespace CGtk
{
	public partial class WCategoria
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Table table;

		private global::Gtk.Entry entryName;

		private global::Gtk.Label label1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btExit;

		private global::Gtk.Button btOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CGtk.WCategoria
			this.Name = "CGtk.WCategoria";
			this.Title = global::Mono.Unix.Catalog.GetString("Añadir categoría");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CGtk.WCategoria.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(6));
			// Container child table.Gtk.Table+TableChild
			this.entryName = new global::Gtk.Entry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '•';
			this.table.Add(this.entryName);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table[this.entryName]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.table.Add(this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table[this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btExit = new global::Gtk.Button();
			this.btExit.CanFocus = true;
			this.btExit.Name = "btExit";
			this.btExit.UseStock = true;
			this.btExit.UseUnderline = true;
			this.btExit.Label = "gtk-cancel";
			this.hbuttonbox1.Add(this.btExit);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btExit]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btOk = new global::Gtk.Button();
			this.btOk.CanFocus = true;
			this.btOk.Name = "btOk";
			this.btOk.UseStock = true;
			this.btOk.UseUnderline = true;
			this.btOk.Label = "gtk-ok";
			this.hbuttonbox1.Add(this.btOk);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btOk]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add(this.hbuttonbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 70;
			this.Show();
		}
	}
}
